env:
  global:
  - COMMIT_AUTHOR_EMAIL: vahid.mardani@gmail.com
language: python
python:
- 3.6
before_install:
- pip install -U pip setuptools wheel
- pip install -r requirements-ci.txt
install: pip install -e .
script: py.test --cov=easycli easycli/tests
after_success: coveralls
deploy:
  provider: pypi
  skip_cleanup: true
  user: Vahid.Mardani
  password:
    secure: jD50RsIRGB+oJBl+CUniXdS0yzVp06sMegVLIk5YQLs6XvGCpx+/F4+0d8uLobduSoM1LPGnFXFsN2iNqlnygXUpzuwMjX5rK+WK2kxEL7ZN3PwqVNNMo8H0o/Gq47I+xGXIzdPP97qa+tIAdvdcw7wcalTdSLGKvton0yL8bz7p6KlyJwUI6bLv8lixWoxFjeGGLAZbgVZ6TanlKfQs/Hiot0H7HGNsC7dukYsSkwtXJpf3Nr6GRb5q1YPKGOKMQvWqxPNusb0uwuY+XYfz6g1Ytd3NQXKnqPWYInCNA619UQDcb5LwoitByUlqti0Zbx6ltibxLqeG0r2bJjiQYVQ1xRpt4ien4bdAZ2XP08H7XU2u4VdukRE0Vea/dAlW/ypXhCFSfjjRuC1WIknXL7nH+xiiqNP/W0sEreTgOeuU9R1hKpaWcq7A8RIVz0eXpoBd26bEjt/54YmxgH7h8YArpcIN/7zPQRFa7aTA/9zZwrdF6EAawpyEeHAPfYIzfuW3nO3ofn2G6jdTeCyUaIanLLDLlQRdXN4GKGUtjrBK+T/xhNxPxhxAgL2MQ7GScAN707+YhxxBFjS0ZTz0eCrwWMQS1+KwX+sf882AKKD0j3lA+l8ALtUJ7gTF73M+CgeJOJEpHh47fJ0yEbMwddWVtomghwIVzrgOAcbLOHk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: pylover/bddcli
    all_branches: true
